### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Wartets** [anviaan/SodiumExtraInformation#5]
### What happened?

Would it be possible to update the mod to the latest version of [Sodium 0.6.0 for NeoForge 1.21.1](https://modrinth.com/mod/sodium/version/mc1.21.1-0.6.0-neoforge), as it is not compatible?

> Great mod though, very useful!

### Loader

forge

### Mod Version

2.2-beta.1

### Minecraft Version

1.21.1

**Comment by anviaan** [comment]
Done
