### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by darkfirehunter** [anviaan/SodiumExtraInformation#7]
### What happened?

Hey, just wanted to say how much I love this mod and was wondering if you would mind updating this for [Sodium 0.6.3 for neoforge](https://www.curseforge.com/minecraft/mc-mods/sodium/files/5970295)  Thanks for you time

### Loader

forge

### Mod Version

2.2-beta.1

### Minecraft Version

1.21.1

**Comment by anviaan** [comment]
Thank you very much for using the mod and for version 1.21.1 on Neoforge it already works with the latest versions of the Sodium  mod, you just have to update :D
